---
apiVersion: v1
kind: Secret
metadata:
  name: ralph-env-secret
type: Opaque
stringData:

  # LRS backend configuration

  ## Elasticsearch LRS backend
  RALPH_BACKENDS__LRS__ES__HOSTS: "https://elastic:<PASSWORD>@data-lake-es-http:9200"

  ## Mongo LRS backend
  # RALPH_BACKENDS__LRS__MONGO__CONNECTION_URI: "mongodb://mongo:27017/"

  # CLI configuration

  ## Elasticsearch data backend
  # RALPH_BACKENDS__DATA__ES__HOSTS: "http://elasticsearch:9200"

  ## Mongo data backend
  # RALPH_BACKENDS__DATA__MONGO__CONNECTION_URI: "mongodb://mongo:27017/"
---
