---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ralph-env-cm
data:

  # LRS backend configuration

  ## Elasticsearch LRS backend
  RALPH_BACKENDS__LRS__ES__DEFAULT_INDEX: "statements"
  RALPH_BACKENDS__LRS__ES__ALLOW_YELLOW_STATUS: "False"
  RALPH_BACKENDS__LRS__ES__CLIENT_OPTIONS__ca_certs: "/usr/local/share/ca-certificates/ca.crt"
  RALPH_BACKENDS__LRS__ES__CLIENT_OPTIONS__verify_certs: "True"
  RALPH_BACKENDS__LRS__ES__LOCALE_ENCODING: "utf8"
  RALPH_BACKENDS__LRS__ES__POINT_IN_TIME_KEEP_ALIVE: "1m"
  RALPH_BACKENDS__LRS__ES__READ_CHUNK_SIZE: "500"
  RALPH_BACKENDS__LRS__ES__REFRESH_AFTER_WRITE: "false"
  RALPH_BACKENDS__LRS__ES__WRITE_CHUNK_SIZE: "500"

  ## Mongo LRS backend
  # RALPH_BACKENDS__LRS__MONGO__DEFAULT_COLLECTION: "foo"
  # RALPH_BACKENDS__LRS__MONGO__DEFAULT_DATABASE: "statements"
  # RALPH_BACKENDS__LRS__MONGO__CLIENT_OPTIONS__document_class: ""
  # RALPH_BACKENDS__LRS__MONGO__CLIENT_OPTIONS__tz_aware: "False"
  # RALPH_BACKENDS__LRS__MONGO__LOCALE_ENCODING: "utf8"
  # RALPH_BACKENDS__LRS__MONGO__READ_CHUNK_SIZE: "500"
  # RALPH_BACKENDS__LRS__MONGO__WRITE_CHUNK_SIZE: "500"

  # CLI configuration

  ## Elasticsearch data backend
  # RALPH_BACKENDS__DATA__ES__DEFAULT_INDEX: "statements"
  # RALPH_BACKENDS__DATA__ES__ALLOW_YELLOW_STATUS: "False"
  # RALPH_BACKENDS__DATA__ES__CLIENT_OPTIONS__ca_certs: "False"
  # RALPH_BACKENDS__DATA__ES__CLIENT_OPTIONS__verify_certs: "False"
  # RALPH_BACKENDS__DATA__ES__LOCALE_ENCODING: "utf8"
  # RALPH_BACKENDS__DATA__ES__POINT_IN_TIME_KEEP_ALIVE: "1m"
  # RALPH_BACKENDS__DATA__ES__READ_CHUNK_SIZE: "500"
  # RALPH_BACKENDS__DATA__ES__REFRESH_AFTER_WRITE: "false"
  # RALPH_BACKENDS__DATA__ES__WRITE_CHUNK_SIZE: "500"

  ## Mongo data backend
  # RALPH_BACKENDS__DATA__MONGO__DEFAULT_COLLECTION: "foo"
  # RALPH_BACKENDS__DATA__MONGO__DEFAULT_DATABASE: "statements"
  # RALPH_BACKENDS__DATA__MONGO__CLIENT_OPTIONS__document_class: ""
  # RALPH_BACKENDS__DATA__MONGO__CLIENT_OPTIONS__tz_aware: "False"
  # RALPH_BACKENDS__DATA__MONGO__LOCALE_ENCODING: "utf8"
  # RALPH_BACKENDS__DATA__MONGO__READ_CHUNK_SIZE: "500"
  # RALPH_BACKENDS__DATA__MONGO__WRITE_CHUNK_SIZE: "500"
---
