name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Generate .env file
      run: make .env

    - name: Build docker containers
      uses: docker/bake-action@v6
      with: 
        load: true
        set: |
          *.cache-from=type=gha
          *.cache-to=type=gha,mode=max    

    - name: Bootstrap project
      run: make .ralph/auth.json es-index

    - name: Lint with black and ruff
      run: make lint

    - name: Run docker services
      run: make run

    - name: Test with pytest
      run: make test

    - name: Check diff coverage
      run: make diff-cover